export type MuscleGroupId = "chest" | "back" | "shoulders" | "biceps" | "triceps" | "legs" | "abs";

export interface MuscleGroupInfo {
  id: MuscleGroupId;
  label: string;
  icon: string;
}

export const MUSCLE_GROUPS: MuscleGroupInfo[] = [
  { id: "chest", label: "Ko'krak mashqlari", icon: "fitness_center" },
  { id: "back", label: "Qanot mashqlari", icon: "rowing" },
  { id: "shoulders", label: "Yelka mashqlari", icon: "sports_gymnastics" },
  { id: "biceps", label: "Qo'l oldi mashqlari", icon: "sports_martial_arts" },
  { id: "triceps", label: "Qo'l orqa mashqlari", icon: "front_hand" },
  { id: "legs", label: "Oyoq mashqlari", icon: "directions_run" },
  { id: "abs", label: "Pres mashqlari", icon: "self_improvement" },
];

export type Equipment = "barbell" | "dumbbell" | "cable" | "machine" | "bodyweight" | "ez-bar";

export const EQUIPMENT_LABELS: Record<Equipment, string> = {
  barbell: "Shtanga",
  dumbbell: "Gantel",
  cable: "Blok Trenajyor",
  machine: "Trenajyor",
  bodyweight: "Tana Og'irligi",
  "ez-bar": "EZ-Shtanga",
};

export type Level = "beginner" | "intermediate" | "expert";

export const LEVEL_LABELS: Record<Level, string> = {
  beginner: "Boshlang'ich",
  intermediate: "O'rta",
  expert: "Yuqori",
};

export interface Exercise {
  id: string;
  name: string;
  englishName: string;
  muscleGroup: MuscleGroupId;
  equipment: Equipment;
  level: Level;
  sets: string;
  reps: string;
  image: string;
  instructions: string[];
}

const IMG_BASE = "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises";

export const EXERCISES: Exercise[] = [
  // Ko'krak
  {
    id: "Barbell_Bench_Press_-_Medium_Grip",
    name: "Shtanga Yotib Zhim (O'rta Ushlab)",
    englishName: "Barbell Bench Press - Medium Grip",
    muscleGroup: "chest",
    equipment: "barbell",
    level: "beginner",
    sets: "4",
    reps: "6-10",
    image: `${IMG_BASE}/Barbell_Bench_Press_-_Medium_Grip/0.jpg`,
    instructions: [
      "Skameykaga yoting, oyoqlaringizni yerga mahkam tiraying, kurak suyaklaringizni orqaga siqing.",
      "Shtangani yelkadan biroz kengroq ushlab, ko'krak markazidan olib chiqing.",
      "Sekin nafas olib, shtangani ko'krakning pastki qismiga qadar tushiring.",
      "Nafasni chiqarib, tirsaklarni tanaga yaqin tutgan holda tepaga itaring.",
    ],
  },
  {
    id: "Incline_Dumbbell_Press",
    name: "Qiya Skameykada Gantel Zhim",
    englishName: "Incline Dumbbell Press",
    muscleGroup: "chest",
    equipment: "dumbbell",
    level: "beginner",
    sets: "4",
    reps: "8-12",
    image: `${IMG_BASE}/Incline_Dumbbell_Press/0.jpg`,
    instructions: [
      "Skameykani 30-45 daraja qiyalikka o'rnating va gantellarni tizzalarga qo'yib o'tiring.",
      "Har ikki oyoq bilan itarib, gantellarni ko'krak sathigacha ko'taring.",
      "Gantellarni yelka chizig'ida ushlab, sekin ko'krakning yuqori qismigacha tushiring.",
      "To'liq nazorat bilan yuqoriga itarib, tepada gantellarni bir-biriga yaqinlashtiring.",
    ],
  },
  {
    id: "Dumbbell_Flyes",
    name: "Gantel Razvedeniya",
    englishName: "Dumbbell Flyes",
    muscleGroup: "chest",
    equipment: "dumbbell",
    level: "beginner",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Dumbbell_Flyes/0.jpg`,
    instructions: [
      "Skameykada yoting, gantellarni ko'krak uzra tutib, tirsaklarni biroz bukilgan holda saqlang.",
      "Tirsak burchagini o'zgartirmasdan, qo'llarni yon tomonlarga yoyib tushiring.",
      "Ko'krak mushaklarida cho'zilishni his qilguningizcha pastga tushiring.",
      "Ko'krak mushaklarini siqib, gantellarni boshlang'ich holatga qaytaring.",
    ],
  },
  {
    id: "Pushups",
    name: "Klassik Otjimaniye (Push-Up)",
    englishName: "Pushups",
    muscleGroup: "chest",
    equipment: "bodyweight",
    level: "beginner",
    sets: "3",
    reps: "12-20",
    image: `${IMG_BASE}/Pushups/0.jpg`,
    instructions: [
      "Qo'llarni yelkadan biroz kengroq qo'yib tayanch holatini oling, tana bir chiziqda bo'lsin.",
      "Qorin va dumba mushaklarini taranglashtirib, tananing egilib ketishiga yo'l qo'ymang.",
      "Tirsaklarni yon tomonga qarab bukib, ko'krak yerga yaqinlashguncha tushing.",
      "Kaftlarni yerga bosib, boshlang'ich holatga qayting.",
    ],
  },
  {
    id: "Dips_-_Chest_Version",
    name: "Bruslarda Tushish (Ko'krakka)",
    englishName: "Dips - Chest Version",
    muscleGroup: "chest",
    equipment: "bodyweight",
    level: "intermediate",
    sets: "3",
    reps: "8-12",
    image: `${IMG_BASE}/Dips_-_Chest_Version/0.jpg`,
    instructions: [
      "Bruslarni ushlab tananing tepasiga chiqing, tanani biroz oldinga egib turing.",
      "Tirsaklarni yon tomonga yoyib, sekin pastga tushing.",
      "Ko'krakda cho'zilish sezilguncha yoki yelka 90 darajaga yetguncha tushing.",
      "Ko'krak mushaklarini ishga solib, boshlang'ich holatga ko'tariling.",
    ],
  },
  {
    id: "Cable_Crossover",
    name: "Blokli Trenajyorda Krossover",
    englishName: "Cable Crossover",
    muscleGroup: "chest",
    equipment: "cable",
    level: "beginner",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Cable_Crossover/0.jpg`,
    instructions: [
      "Ikkala blok tutqichini yuqoriga o'rnatib, tanani biroz oldinga egib, markazda turing.",
      "Tirsaklarni yengil bukilgan holatda tutib, qo'llarni pastga va oldinga tortib olib keling.",
      "Qo'llarni qorin oldida kesishtirib, ko'krakni maksimal siqing.",
      "Nazorat ostida qo'llarni boshlang'ich holatga qaytaring.",
    ],
  },

  {
    id: "Dumbbell_Bench_Press",
    name: "Gantel Yotib Zhim",
    englishName: "Dumbbell Bench Press",
    muscleGroup: "chest",
    equipment: "dumbbell",
    level: "beginner",
    sets: "4",
    reps: "8-12",
    image: `${IMG_BASE}/Dumbbell_Bench_Press/0.jpg`,
    instructions: [
      "Skameykaga yoting, gantellarni ko'krak yonida, kaftlar oldinga qaragan holda tuting.",
      "Gantellarni bir vaqtda tik yuqoriga, qo'llar to'liq yozilguncha itaring.",
      "Harakat cho'qqisida gantellarni bir-biriga yaqinlashtirib, ko'krakni siqing.",
      "Nazorat ostida gantellarni ko'krak sathiga qaytarib tushiring.",
    ],
  },
  {
    id: "Barbell_Incline_Bench_Press_-_Medium_Grip",
    name: "Qiya Skameykada Shtanga Zhim",
    englishName: "Barbell Incline Bench Press",
    muscleGroup: "chest",
    equipment: "barbell",
    level: "intermediate",
    sets: "4",
    reps: "6-10",
    image: `${IMG_BASE}/Barbell_Incline_Bench_Press_-_Medium_Grip/0.jpg`,
    instructions: [
      "Skameykani 30-45 daraja qiyalikka o'rnatib yoting, shtangani yelkadan biroz kengroq ushlang.",
      "Shtangani tayanchdan olib, qo'llarni to'liq yozib ko'krakning yuqori qismi uzra tuting.",
      "Sekin nafas olib, shtangani ko'krakning yuqori qismiga qadar tushiring.",
      "Nafas chiqarib, shtangani boshlang'ich holatga qaytarib itaring.",
    ],
  },
  {
    id: "Decline_Dumbbell_Bench_Press",
    name: "Teskari Qiya Skameykada Gantel Zhim",
    englishName: "Decline Dumbbell Bench Press",
    muscleGroup: "chest",
    equipment: "dumbbell",
    level: "intermediate",
    sets: "3",
    reps: "8-12",
    image: `${IMG_BASE}/Decline_Dumbbell_Bench_Press/0.jpg`,
    instructions: [
      "Teskari qiya skameykaga yotib, oyoqlarni tayanchga mahkamlang.",
      "Gantellarni ko'krak yonida, kaftlar oldinga qaragan holda tuting.",
      "Gantellarni tik yuqoriga, qo'llar to'liq yozilguncha itaring.",
      "Nazorat ostida gantellarni ko'krakning pastki qismiga qaytaring.",
    ],
  },
  {
    id: "Butterfly",
    name: "Trenajyorda Kapalak (Pec Deck)",
    englishName: "Butterfly",
    muscleGroup: "chest",
    equipment: "machine",
    level: "beginner",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Butterfly/0.jpg`,
    instructions: [
      "Trenajyorga o'tirib, orqani tayanchga bosing, bilaklarni yostiqchalarga qo'ying.",
      "Tirsaklarni yelka sathida tutib, qo'llarni oldinga, bir-biriga yaqinlashtiring.",
      "Qo'llar birlashganda ko'krak mushaklarini bir zum siqib turing.",
      "Nazorat ostida qo'llarni yon tomonga, boshlang'ich holatga qaytaring.",
    ],
  },
  {
    id: "Incline_Dumbbell_Flyes",
    name: "Qiya Skameykada Gantel Razvedeniya",
    englishName: "Incline Dumbbell Flyes",
    muscleGroup: "chest",
    equipment: "dumbbell",
    level: "beginner",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Incline_Dumbbell_Flyes/0.jpg`,
    instructions: [
      "Skameykani 30-45 daraja qiyalikka o'rnatib yoting, gantellarni ko'krak uzra tuting.",
      "Tirsaklarni yengil bukilgan holda saqlab, qo'llarni yon tomonlarga yoyib tushiring.",
      "Ko'krakning yuqori qismida cho'zilishni his qilguningizcha pastga tushiring.",
      "Ko'krak kuchi bilan gantellarni yana tepada birlashtiring.",
    ],
  },
  {
    id: "Straight-Arm_Dumbbell_Pullover",
    name: "Gantel Pullover",
    englishName: "Straight-Arm Dumbbell Pullover",
    muscleGroup: "chest",
    equipment: "dumbbell",
    level: "intermediate",
    sets: "3",
    reps: "10-12",
    image: `${IMG_BASE}/Straight-Arm_Dumbbell_Pullover/0.jpg`,
    instructions: [
      "Skameykaga ko'ndalang yoki bo'ylama yotib, bitta gantelni ikki kaft bilan ko'krak uzra tuting.",
      "Qo'llarni deyarli to'g'ri tutgan holda gantelni bosh ortiga, sekin pastga tushiring.",
      "Ko'krak va qanot mushaklarida cho'zilishni his qilguncha tushiring.",
      "Xuddi shu yoy bo'ylab gantelni ko'krak uzra boshlang'ich holatga qaytaring.",
    ],
  },

  // Orqa
  {
    id: "Pullups",
    name: "Turnikda Tortilish",
    englishName: "Pullups",
    muscleGroup: "back",
    equipment: "bodyweight",
    level: "intermediate",
    sets: "4",
    reps: "6-10",
    image: `${IMG_BASE}/Pullups/0.jpg`,
    instructions: [
      "Turnikni yelkadan kengroq ushlab, tananing to'liq osilishiga yo'l qo'ying.",
      "Kurak suyaklarini pastga va orqaga tortib harakatni boshlang.",
      "Iyagingiz turnikdan oshguncha tanani yuqoriga tortib chiqing.",
      "Sekin va nazorat ostida boshlang'ich holatga tushing.",
    ],
  },
  {
    id: "Bent_Over_Barbell_Row",
    name: "Egilgan Holda Shtanga Tortish",
    englishName: "Bent Over Barbell Row",
    muscleGroup: "back",
    equipment: "barbell",
    level: "beginner",
    sets: "4",
    reps: "8-10",
    image: `${IMG_BASE}/Bent_Over_Barbell_Row/0.jpg`,
    instructions: [
      "Oyoqlarni yelka kengligida qo'yib, tizzalarni biroz bukib, tanani 45 daraja egib turing.",
      "Orqa tekis holatda, shtangani yelkadan biroz kengroq ushlang.",
      "Tirsaklarni orqaga tortib, shtangani qorin pastki qismiga qadar ko'taring.",
      "Kuraklarni siqib, sekin boshlang'ich holatga tushiring.",
    ],
  },
  {
    id: "Wide-Grip_Lat_Pulldown",
    name: "Keng Ushlab Yuqori Blok Tortish",
    englishName: "Wide-Grip Lat Pulldown",
    muscleGroup: "back",
    equipment: "cable",
    level: "beginner",
    sets: "4",
    reps: "10-12",
    image: `${IMG_BASE}/Wide-Grip_Lat_Pulldown/0.jpg`,
    instructions: [
      "Trenajyorda o'tirib, tayanchni tizzalar ustiga mahkamlang, tutqichni yelkadan kengroq ushlang.",
      "Ko'krakni biroz ko'tarib, tortish paytida orqaga yaslanmang.",
      "Tutqichni ko'krakning yuqori qismiga qadar tortib tushiring, kuraklarni siqing.",
      "Nazorat ostida tutqichni yuqoriga, boshlang'ich holatga qaytaring.",
    ],
  },
  {
    id: "Seated_Cable_Rows",
    name: "O'tirib Blokda Tortish",
    englishName: "Seated Cable Rows",
    muscleGroup: "back",
    equipment: "cable",
    level: "beginner",
    sets: "3",
    reps: "10-12",
    image: `${IMG_BASE}/Seated_Cable_Rows/0.jpg`,
    instructions: [
      "Trenajyorda o'tirib, tizzalarni yengil bukib, oyoqlarni tayanchga tiraying.",
      "Orqani tik tutgan holda tutqichni ikki qo'l bilan ushlang.",
      "Tirsaklarni tanaga yaqin tutib, tutqichni qorin tomon tortib keling, kuraklarni siqing.",
      "Sekin nazorat bilan qo'llarni oldinga, boshlang'ich holatga qaytaring.",
    ],
  },
  {
    id: "One-Arm_Dumbbell_Row",
    name: "Bir Qo'lda Gantel Tortish",
    englishName: "One-Arm Dumbbell Row",
    muscleGroup: "back",
    equipment: "dumbbell",
    level: "beginner",
    sets: "3/qo'l",
    reps: "10-12",
    image: `${IMG_BASE}/One-Arm_Dumbbell_Row/0.jpg`,
    instructions: [
      "Bir tizza va qo'lni skameykaga tirab, orqani tekis tuting.",
      "Ikkinchi qo'lda gantelni tutib, qo'lni to'liq osiltiring.",
      "Tirsakni orqaga tortib, gantelni bel yoniga qadar ko'taring, kurakni siqing.",
      "Nazorat ostida gantelni pastga, boshlang'ich holatga tushiring.",
    ],
  },
  {
    id: "Barbell_Deadlift",
    name: "Stanova Tyaga (Ko'tarish)",
    englishName: "Barbell Deadlift",
    muscleGroup: "back",
    equipment: "barbell",
    level: "intermediate",
    sets: "4",
    reps: "5-8",
    image: `${IMG_BASE}/Barbell_Deadlift/0.jpg`,
    instructions: [
      "Shtangaga oyoq yelka kengligida yaqin turing, orqani tekis tutib pastga egiling.",
      "Shtangani yelkadan biroz kengroq ushlab, ko'krakni ko'tarib, belni tekis saqlang.",
      "Oyoq va son mushaklari kuchi bilan shtangani tanaga yaqin tutib tik turguningizcha ko'taring.",
      "Bel va orqani egmasdan, harakatni teskari tartibda pastga tushirib boshlang'ich holatga qayting.",
    ],
  },

  {
    id: "T-Bar_Row_with_Handle",
    name: "T-Shtanga Tortish",
    englishName: "T-Bar Row with Handle",
    muscleGroup: "back",
    equipment: "barbell",
    level: "intermediate",
    sets: "4",
    reps: "8-10",
    image: `${IMG_BASE}/T-Bar_Row_with_Handle/0.jpg`,
    instructions: [
      "Shtanga ustida turib, tanani 45 daraja oldinga egib, tutqichni ikki qo'l bilan ushlang.",
      "Orqani tekis, ko'krakni ko'tarilgan holatda saqlang.",
      "Tirsaklarni orqaga tortib, og'irlikni ko'krak tomon ko'taring, kuraklarni siqing.",
      "Nazorat ostida og'irlikni pastga, boshlang'ich holatga tushiring.",
    ],
  },
  {
    id: "Chin-Up",
    name: "Teskari Ushlab Tortilish (Chin-Up)",
    englishName: "Chin-Up",
    muscleGroup: "back",
    equipment: "bodyweight",
    level: "intermediate",
    sets: "3",
    reps: "6-10",
    image: `${IMG_BASE}/Chin-Up/0.jpg`,
    instructions: [
      "Turnikni yelka kengligida, kaftlar o'zingizga qaragan holda ushlang.",
      "Tananing to'liq osilishiga yo'l qo'yib, kuraklarni pastga torting.",
      "Iyagingiz turnikdan oshguncha tortilib chiqing — bitseps va qanot birga ishlaydi.",
      "Sekin, nazorat ostida boshlang'ich holatga tushing.",
    ],
  },
  {
    id: "Close-Grip_Front_Lat_Pulldown",
    name: "Tor Ushlab Yuqori Blok Tortish",
    englishName: "Close-Grip Front Lat Pulldown",
    muscleGroup: "back",
    equipment: "cable",
    level: "beginner",
    sets: "3",
    reps: "10-12",
    image: `${IMG_BASE}/Close-Grip_Front_Lat_Pulldown/0.jpg`,
    instructions: [
      "Trenajyorda o'tirib, tutqichni yelka kengligidan torroq ushlang.",
      "Ko'krakni ko'tarib, tanani biroz orqaga egib turing.",
      "Tutqichni ko'krakning yuqori qismiga qadar tortib tushiring, tirsaklarni tanaga yaqin tuting.",
      "Nazorat ostida tutqichni yuqoriga qaytaring, qanot mushaklarida cho'zilishni his qiling.",
    ],
  },
  {
    id: "Straight-Arm_Pulldown",
    name: "To'g'ri Qo'llar bilan Blok Tortish",
    englishName: "Straight-Arm Pulldown",
    muscleGroup: "back",
    equipment: "cable",
    level: "intermediate",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Straight-Arm_Pulldown/0.jpg`,
    instructions: [
      "Yuqori blok qarshisida turib, tutqichni yelka kengligida, qo'llar to'g'ri holda ushlang.",
      "Tanani biroz oldinga egib, qorinni taranglashtiring.",
      "Qo'llarni bukmasdan, tutqichni yoy bo'ylab sonlargacha pastga torting.",
      "Qanot mushaklarini siqib, nazorat ostida boshlang'ich holatga qaytaring.",
    ],
  },
  {
    id: "Hyperextensions_Back_Extensions",
    name: "Giperekstenziya",
    englishName: "Hyperextensions (Back Extensions)",
    muscleGroup: "back",
    equipment: "bodyweight",
    level: "beginner",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Hyperextensions_Back_Extensions/0.jpg`,
    instructions: [
      "Trenajyorga yuztuban joylashib, to'piqlarni tayanch ostiga mahkamlang.",
      "Qo'llarni ko'krakda kesishtirib yoki bosh ortiga qo'yib, tanani pastga egib tushiring.",
      "Bel va orqa mushaklar kuchi bilan tanani oyoqlar bilan bir chiziqqa qadar ko'taring.",
      "Yuqorida ortiqcha bukilmasdan, nazorat ostida pastga qaytaring.",
    ],
  },

  // Yelka
  {
    id: "Standing_Military_Press",
    name: "Tik Turib Shtanga Bosh Uzra Zhim",
    englishName: "Standing Military Press",
    muscleGroup: "shoulders",
    equipment: "barbell",
    level: "beginner",
    sets: "4",
    reps: "6-10",
    image: `${IMG_BASE}/Standing_Military_Press/0.jpg`,
    instructions: [
      "Oyoqlarni yelka kengligida qo'yib, shtangani yelka sathida, kaftlar oldinga qaragan holda ushlang.",
      "Qorin va dumba mushaklarini taranglashtirib, tanani barqaror tuting.",
      "Shtangani boshdan bir oz nari o'tkazib, tik yuqoriga qo'llar to'liq yozilguncha itaring.",
      "Nazorat ostida shtangani yelka sathiga qaytaring.",
    ],
  },
  {
    id: "Arnold_Dumbbell_Press",
    name: "Arnold Zhimi",
    englishName: "Arnold Dumbbell Press",
    muscleGroup: "shoulders",
    equipment: "dumbbell",
    level: "intermediate",
    sets: "3",
    reps: "8-12",
    image: `${IMG_BASE}/Arnold_Dumbbell_Press/0.jpg`,
    instructions: [
      "O'tirib yoki tik turib, gantellarni kaftlar tanaga qaragan holda ko'krak oldida tuting.",
      "Gantellarni yuqoriga ko'tarayotganda bilaklarni asta tashqariga aylantiring.",
      "Harakat oxirida kaftlar oldinga qaragan holda qo'llarni to'liq yozing.",
      "Xuddi shu aylanma yo'l bilan gantellarni boshlang'ich holatga qaytaring.",
    ],
  },
  {
    id: "Side_Lateral_Raise",
    name: "Gantelni Yon Tomonga Ko'tarish",
    englishName: "Side Lateral Raise",
    muscleGroup: "shoulders",
    equipment: "dumbbell",
    level: "beginner",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Side_Lateral_Raise/0.jpg`,
    instructions: [
      "Tik turib, gantellarni tana yoniga tutib, tirsaklarni yengil bukilgan holatda saqlang.",
      "Qo'llarni yon tomonga, yelka sathigacha ko'taring, kaftlar yerga qaragan bo'lsin.",
      "Harakatni tanani tebratmasdan, faqat yelka kuchi bilan bajaring.",
      "Nazorat ostida gantellarni sekin pastga tushiring.",
    ],
  },
  {
    id: "Front_Dumbbell_Raise",
    name: "Gantelni Oldinga Ko'tarish",
    englishName: "Front Dumbbell Raise",
    muscleGroup: "shoulders",
    equipment: "dumbbell",
    level: "beginner",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Front_Dumbbell_Raise/0.jpg`,
    instructions: [
      "Tik turib, gantellarni tana oldida, kaftlar sonlarga qaragan holda ushlang.",
      "Bir yoki ikkala qo'lni tirsak biroz bukilgan holda oldinga, yelka sathigacha ko'taring.",
      "Harakat cho'qqisida bir zum ushlab turing, tananing ortga egilishiga yo'l qo'ymang.",
      "Sekin nazorat bilan gantellarni boshlang'ich holatga tushiring.",
    ],
  },
  {
    id: "Face_Pull",
    name: "Yuzga Tortish (Face Pull)",
    englishName: "Face Pull",
    muscleGroup: "shoulders",
    equipment: "cable",
    level: "intermediate",
    sets: "3",
    reps: "15-20",
    image: `${IMG_BASE}/Face_Pull/0.jpg`,
    instructions: [
      "Blokni yuz sathida o'rnatib, arqon tutqichni ikki uchidan ushlang.",
      "Tirsaklarni yuqori va yon tomonga ko'tarib, arqonni yuzga tomon tortib keling.",
      "Tortish paytida bilaklarni tashqariga aylantirib, orqa yelka mushaklarini siqing.",
      "Nazorat ostida qo'llarni oldinga, boshlang'ich holatga qaytaring.",
    ],
  },
  {
    id: "Upright_Barbell_Row",
    name: "Shtangani Tik Tortish",
    englishName: "Upright Barbell Row",
    muscleGroup: "shoulders",
    equipment: "barbell",
    level: "beginner",
    sets: "3",
    reps: "10-12",
    image: `${IMG_BASE}/Upright_Barbell_Row/0.jpg`,
    instructions: [
      "Shtangani yelka kengligida ushlab, tana oldida osiltirib tik turing.",
      "Tirsaklarni yuqoriga yo'naltirib, shtangani iyak sathigacha ko'taring.",
      "Shtangani tanaga yaqin tutib, yelka va trapetsiya mushaklarini ishga soling.",
      "Nazorat ostida shtangani boshlang'ich holatga tushiring.",
    ],
  },

  {
    id: "Seated_Dumbbell_Press",
    name: "O'tirib Gantel Zhim",
    englishName: "Seated Dumbbell Press",
    muscleGroup: "shoulders",
    equipment: "dumbbell",
    level: "beginner",
    sets: "4",
    reps: "8-12",
    image: `${IMG_BASE}/Seated_Dumbbell_Press/0.jpg`,
    instructions: [
      "Suyanchig'i tik skameykaga o'tirib, gantellarni yelka sathida, kaftlar oldinga qaragan holda tuting.",
      "Qorinni taranglashtirib, gantellarni tik yuqoriga itaring.",
      "Tepada gantellarni bir-biriga yaqinlashtiring, lekin urishtirmang.",
      "Nazorat ostida gantellarni yelka sathiga qaytaring.",
    ],
  },
  {
    id: "Reverse_Flyes",
    name: "Egilgan Holda Teskari Razvedeniya",
    englishName: "Reverse Flyes",
    muscleGroup: "shoulders",
    equipment: "dumbbell",
    level: "beginner",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Reverse_Flyes/0.jpg`,
    instructions: [
      "Tanani deyarli yerga parallel bo'lguncha oldinga egib, gantellarni osiltirib tuting.",
      "Tirsaklarni yengil bukilgan holda saqlab, qo'llarni yon tomonlarga yoyib ko'taring.",
      "Harakat cho'qqisida kuraklarni siqib, orqa yelka mushaklarini ishga soling.",
      "Nazorat ostida gantellarni pastga, boshlang'ich holatga tushiring.",
    ],
  },
  {
    id: "Barbell_Shrug",
    name: "Shtanga bilan Shrag (Trapetsiya)",
    englishName: "Barbell Shrug",
    muscleGroup: "shoulders",
    equipment: "barbell",
    level: "beginner",
    sets: "4",
    reps: "10-15",
    image: `${IMG_BASE}/Barbell_Shrug/0.jpg`,
    instructions: [
      "Shtangani yelka kengligida ushlab, tana oldida osiltirib tik turing.",
      "Qo'llarni bukmasdan, yelkalarni tik yuqoriga, quloqlar tomon ko'taring.",
      "Cho'qqida trapetsiya mushaklarini bir zum siqib turing.",
      "Sekin nazorat bilan yelkalarni pastga tushiring.",
    ],
  },
  {
    id: "Cable_Rear_Delt_Fly",
    name: "Blokda Orqa Delta Razvedeniya",
    englishName: "Cable Rear Delt Fly",
    muscleGroup: "shoulders",
    equipment: "cable",
    level: "intermediate",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Cable_Rear_Delt_Fly/0.jpg`,
    instructions: [
      "Ikki blokning tutqichlarini kesishtirib, qarama-qarshi qo'llar bilan ushlang.",
      "Tirsaklarni yengil bukilgan holda tutib, qo'llarni yon-orqaga yoyib torting.",
      "Harakat cho'qqisida orqa yelka mushaklarini siqing.",
      "Nazorat ostida qo'llarni oldinga, boshlang'ich holatga qaytaring.",
    ],
  },
  {
    id: "Smith_Machine_Overhead_Shoulder_Press",
    name: "Smit Trenajyorida Yelka Zhim",
    englishName: "Smith Machine Overhead Shoulder Press",
    muscleGroup: "shoulders",
    equipment: "machine",
    level: "beginner",
    sets: "4",
    reps: "8-12",
    image: `${IMG_BASE}/Smith_Machine_Overhead_Shoulder_Press/0.jpg`,
    instructions: [
      "Skameykani Smit trenajyori ostiga qo'yib, grif yelka sathida bo'lishini sozlang.",
      "Grifni yelkadan biroz kengroq ushlab, qulfdan chiqaring.",
      "Grifni tik yuqoriga, qo'llar to'liq yozilguncha itaring.",
      "Nazorat ostida grifni iyak sathigacha tushiring va harakatni takrorlang.",
    ],
  },

  // Biceps
  {
    id: "Barbell_Curl",
    name: "Shtanga bilan Bilak Bukish",
    englishName: "Barbell Curl",
    muscleGroup: "biceps",
    equipment: "barbell",
    level: "beginner",
    sets: "3",
    reps: "8-12",
    image: `${IMG_BASE}/Barbell_Curl/0.jpg`,
    instructions: [
      "Oyoqlarni yelka kengligida qo'yib, shtangani kaftlar oldinga qaragan holda ushlang.",
      "Tirsaklarni tanaga yaqin tutib, faqat bilaklarni bukib shtangani ko'taring.",
      "Harakat cho'qqisida bitseps mushaklarini siqing, tananing tebranishiga yo'l qo'ymang.",
      "Sekin nazorat bilan shtangani boshlang'ich holatga tushiring.",
    ],
  },
  {
    id: "Seated_Dumbbell_Curl",
    name: "O'tirib Gantel bilan Bilak Bukish",
    englishName: "Seated Dumbbell Curl",
    muscleGroup: "biceps",
    equipment: "dumbbell",
    level: "beginner",
    sets: "3",
    reps: "10-12",
    image: `${IMG_BASE}/Seated_Dumbbell_Curl/0.jpg`,
    instructions: [
      "Skameykada o'tirib, gantellarni yon tomonda, kaftlar tanaga qaragan holda tuting.",
      "Bilaklarni bukayotganda kaftni tashqariga aylantirib, ko'targan qo'lni yelkaga yaqinlashtiring.",
      "Tirsakni harakat davomida qimirlatmang, faqat bilak ishlasin.",
      "Nazorat ostida gantelni boshlang'ich holatga tushiring va navbatma-navbat bajaring.",
    ],
  },
  {
    id: "Hammer_Curls",
    name: "Bolg'a Uslubida Bukish (Hammer Curl)",
    englishName: "Hammer Curls",
    muscleGroup: "biceps",
    equipment: "dumbbell",
    level: "beginner",
    sets: "3",
    reps: "10-12",
    image: `${IMG_BASE}/Hammer_Curls/0.jpg`,
    instructions: [
      "Tik turib, gantellarni kaftlar bir-biriga qaragan holda tana yonida tuting.",
      "Kaft holatini o'zgartirmasdan, gantellarni yelkaga tomon bukib ko'taring.",
      "Tirsaklarni tanaga yaqin tutib, harakatni faqat bilak kuchi bilan bajaring.",
      "Sekin nazorat bilan gantellarni boshlang'ich holatga tushiring.",
    ],
  },
  {
    id: "Preacher_Curl",
    name: "Skameykada Bilak Bukish (Preacher Curl)",
    englishName: "Preacher Curl",
    muscleGroup: "biceps",
    equipment: "barbell",
    level: "beginner",
    sets: "3",
    reps: "10-12",
    image: `${IMG_BASE}/Preacher_Curl/0.jpg`,
    instructions: [
      "Preacher skameykasiga o'tirib, qo'llaringizni qo'ltiq ostigacha tayanchga qo'ying.",
      "Shtanga yoki EZ-shtangani kaftlar yuqoriga qaragan holda ushlang.",
      "Faqat bilaklarni bukib, shtangani yelka tomon ko'taring, tirsaklarni tayanchdan uzmang.",
      "Nazorat ostida shtangani to'liq yozilguncha pastga tushiring.",
    ],
  },
  {
    id: "Concentration_Curls",
    name: "Konsentratsiyali Bukish",
    englishName: "Concentration Curls",
    muscleGroup: "biceps",
    equipment: "dumbbell",
    level: "beginner",
    sets: "3/qo'l",
    reps: "12-15",
    image: `${IMG_BASE}/Concentration_Curls/0.jpg`,
    instructions: [
      "Skameykaga o'tirib, tirsakni son ichki qismiga tirab gantelni ushlang.",
      "Tanani biroz oldinga egib, qo'lni to'liq osiltiring.",
      "Faqat bilak kuchi bilan gantelni yelka tomon bukib ko'taring va bitsepsni siqing.",
      "Sekin nazorat bilan gantelni boshlang'ich holatga tushiring.",
    ],
  },
  {
    id: "Standing_Biceps_Cable_Curl",
    name: "Blokda Tik Turib Bilak Bukish",
    englishName: "Standing Biceps Cable Curl",
    muscleGroup: "biceps",
    equipment: "cable",
    level: "beginner",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Standing_Biceps_Cable_Curl/0.jpg`,
    instructions: [
      "Pastki blokka tutqich o'rnatib, undan bir necha qadam nariga turing.",
      "Tirsaklarni tanaga yaqin tutib, tutqichni yelka tomon bukib tortib keling.",
      "Harakat cho'qqisida bitseps mushaklarini siqing.",
      "Nazorat ostida tutqichni boshlang'ich holatga qaytaring.",
    ],
  },

  {
    id: "EZ-Bar_Curl",
    name: "EZ-Shtanga bilan Bilak Bukish",
    englishName: "EZ-Bar Curl",
    muscleGroup: "biceps",
    equipment: "ez-bar",
    level: "beginner",
    sets: "3",
    reps: "10-12",
    image: `${IMG_BASE}/EZ-Bar_Curl/0.jpg`,
    instructions: [
      "EZ-shtanganing egilgan qismidan, kaftlar biroz ichkariga qaragan holda ushlang.",
      "Tirsaklarni tanaga yaqin tutib, shtangani yelka tomon bukib ko'taring.",
      "Cho'qqida bitseps mushaklarini siqing, bilaklardagi ortiqcha zo'riqish EZ-grif tufayli kam bo'ladi.",
      "Sekin nazorat bilan shtangani to'liq yozilguncha tushiring.",
    ],
  },
  {
    id: "Incline_Dumbbell_Curl",
    name: "Qiya Skameykada Gantel Bukish",
    englishName: "Incline Dumbbell Curl",
    muscleGroup: "biceps",
    equipment: "dumbbell",
    level: "intermediate",
    sets: "3",
    reps: "10-12",
    image: `${IMG_BASE}/Incline_Dumbbell_Curl/0.jpg`,
    instructions: [
      "Skameykani 45-60 daraja qiyalikka o'rnatib, orqani tayanchga bosib o'tiring.",
      "Gantellarni pastda to'liq osiltirib, bitsepsda cho'zilishni his qiling.",
      "Tirsaklarni orqada tutgan holda gantellarni yelka tomon bukib ko'taring.",
      "Sekin nazorat bilan gantellarni to'liq yozilguncha tushiring.",
    ],
  },
  {
    id: "Cable_Hammer_Curls_-_Rope_Attachment",
    name: "Blokda Arqon bilan Bolg'a Bukish",
    englishName: "Cable Hammer Curls - Rope Attachment",
    muscleGroup: "biceps",
    equipment: "cable",
    level: "beginner",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Cable_Hammer_Curls_-_Rope_Attachment/0.jpg`,
    instructions: [
      "Pastki blokka arqon tutqich o'rnatib, ikki uchidan kaftlar bir-biriga qaragan holda ushlang.",
      "Tirsaklarni tanaga yaqin, harakatsiz tuting.",
      "Arqonni yelka tomon bukib torting, kaft holatini o'zgartirmang.",
      "Nazorat ostida qo'llarni to'liq yozilguncha tushiring.",
    ],
  },
  {
    id: "Zottman_Curl",
    name: "Zottman Bukish",
    englishName: "Zottman Curl",
    muscleGroup: "biceps",
    equipment: "dumbbell",
    level: "intermediate",
    sets: "3",
    reps: "10-12",
    image: `${IMG_BASE}/Zottman_Curl/0.jpg`,
    instructions: [
      "Gantellarni tana yonida, kaftlar oldinga qaragan holda tutib tik turing.",
      "Gantellarni yelka tomon bukib ko'taring — bu bitseps qismi.",
      "Tepada kaftlarni pastga qaratib aylantiring va shu holatda sekin tushiring.",
      "Pastda kaftlarni yana oldinga qaratib, harakatni takrorlang — bilak mushaklari ham ishlaydi.",
    ],
  },
  {
    id: "Spider_Curl",
    name: "Spider Bukish",
    englishName: "Spider Curl",
    muscleGroup: "biceps",
    equipment: "barbell",
    level: "intermediate",
    sets: "3",
    reps: "10-12",
    image: `${IMG_BASE}/Spider_Curl/0.jpg`,
    instructions: [
      "Qiya skameykaga yuztuban yotib, qo'llarni tik pastga osiltiring.",
      "Shtangani yelka kengligida, kaftlar yuqoriga qaragan holda ushlang.",
      "Tirsaklarni qimirlatmasdan, shtangani yelka tomon bukib ko'taring.",
      "Cho'qqida bitsepsni qattiq siqib, sekin boshlang'ich holatga tushiring.",
    ],
  },

  // Triceps
  {
    id: "Close-Grip_Barbell_Bench_Press",
    name: "Tor Ushlab Shtanga Yotib Zhim",
    englishName: "Close-Grip Barbell Bench Press",
    muscleGroup: "triceps",
    equipment: "barbell",
    level: "beginner",
    sets: "4",
    reps: "8-10",
    image: `${IMG_BASE}/Close-Grip_Barbell_Bench_Press/0.jpg`,
    instructions: [
      "Skameykaga yoting, shtangani yelka kengligidan torroq ushlang.",
      "Tirsaklarni tanaga yaqin tutib, shtangani ko'krakning pastki qismiga tushiring.",
      "Tirsaklar tashqariga yoyilmasin, faqat triceps kuchi bilan yuqoriga iting.",
      "Qo'llar to'liq yozilguncha shtangani ko'tarib, boshlang'ich holatni tiklang.",
    ],
  },
  {
    id: "Triceps_Pushdown",
    name: "Blokda Tricepsni Pastga Itarish",
    englishName: "Triceps Pushdown",
    muscleGroup: "triceps",
    equipment: "cable",
    level: "beginner",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Triceps_Pushdown/0.jpg`,
    instructions: [
      "Yuqori blokka tutqich o'rnatib, tirsaklarni tanaga yaqin, 90 daraja bukilgan holda tuting.",
      "Tirsaklarni qimirlatmasdan, tutqichni to'liq pastga, qo'llar yozilguncha itaring.",
      "Harakat pastida triceps mushaklarini bir zum siqing.",
      "Nazorat ostida tutqichni yuqoriga, boshlang'ich holatga qaytaring.",
    ],
  },
  {
    id: "Lying_Triceps_Press",
    name: "Yotib Peshonaga Tushirish (Skull Crusher)",
    englishName: "Lying Triceps Press",
    muscleGroup: "triceps",
    equipment: "ez-bar",
    level: "intermediate",
    sets: "3",
    reps: "10-12",
    image: `${IMG_BASE}/Lying_Triceps_Press/0.jpg`,
    instructions: [
      "Skameykaga yoting, EZ-shtangani qo'llar tepada, ko'krak uzra tik tutib ushlang.",
      "Faqat tirsaklarni bukib, shtangani peshona yoki bosh ortiga sekin tushiring.",
      "Tirsaklarni harakat davomida bir joyda, tanaga perpendikulyar tuting.",
      "Triceps kuchi bilan shtangani boshlang'ich holatga qaytaring.",
    ],
  },
  {
    id: "Standing_Dumbbell_Triceps_Extension",
    name: "Tik Turib Gantelni Bosh Uzra Cho'zish",
    englishName: "Standing Dumbbell Triceps Extension",
    muscleGroup: "triceps",
    equipment: "dumbbell",
    level: "beginner",
    sets: "3",
    reps: "10-12",
    image: `${IMG_BASE}/Standing_Dumbbell_Triceps_Extension/0.jpg`,
    instructions: [
      "Tik turib, bitta gantelni ikki qo'l bilan bosh uzra ko'tarib ushlang.",
      "Tirsaklarni yuqorida, boshga yaqin tutib, faqat bilaklarni bukib gantelni ensa ortiga tushiring.",
      "Tirsaklarni tashqariga yoyilishiga yo'l qo'ymang.",
      "Triceps kuchi bilan gantelni yana bosh uzra to'liq yozilguncha ko'taring.",
    ],
  },
  {
    id: "Dips_-_Triceps_Version",
    name: "Bruslarda Tushish (Tricepsga)",
    englishName: "Dips - Triceps Version",
    muscleGroup: "triceps",
    equipment: "bodyweight",
    level: "beginner",
    sets: "3",
    reps: "8-12",
    image: `${IMG_BASE}/Dips_-_Triceps_Version/0.jpg`,
    instructions: [
      "Bruslarni ushlab, tanani tik holatda tutib tepaga chiqing.",
      "Tirsaklarni tanaga yaqin, orqaga qarab bukib, sekin pastga tushing.",
      "Yelka bilan tirsak bir chiziqqa yetguncha yoki qulaylik chegarasigacha tushing.",
      "Triceps kuchi bilan tananing tepasiga qaytaring, tirsaklarni yon tomonga yoymang.",
    ],
  },
  {
    id: "Tricep_Dumbbell_Kickback",
    name: "Egilgan Holda Gantel Kikbek",
    englishName: "Tricep Dumbbell Kickback",
    muscleGroup: "triceps",
    equipment: "dumbbell",
    level: "beginner",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Tricep_Dumbbell_Kickback/0.jpg`,
    instructions: [
      "Bir tizza va qo'lni skameykaga tirab, tanani yerga parallel tuting.",
      "Gantelli qo'lning tirsagini tanaga yaqin, 90 daraja bukilgan holda ushlang.",
      "Faqat bilakni yozib, gantelni orqaga, qo'l to'liq tekis bo'lguncha iting.",
      "Harakat oxirida triceps mushagini siqib, nazorat ostida boshlang'ich holatga qayting.",
    ],
  },

  {
    id: "Bench_Dips",
    name: "Skameykada Orqa Tayanch (Bench Dips)",
    englishName: "Bench Dips",
    muscleGroup: "triceps",
    equipment: "bodyweight",
    level: "beginner",
    sets: "3",
    reps: "10-15",
    image: `${IMG_BASE}/Bench_Dips/0.jpg`,
    instructions: [
      "Skameykaga orqa bilan o'girilib, kaftlarni skameyka chetiga yelka kengligida qo'ying.",
      "Oyoqlarni oldinga uzatib, dumbani skameykadan chiqaring.",
      "Tirsaklarni orqaga bukib, tanani 90 darajagacha pastga tushiring.",
      "Triceps kuchi bilan tanani yuqoriga, qo'llar to'liq yozilguncha ko'taring.",
    ],
  },
  {
    id: "Cable_Rope_Overhead_Triceps_Extension",
    name: "Blokda Arqon bilan Bosh Uzra Cho'zish",
    englishName: "Cable Rope Overhead Triceps Extension",
    muscleGroup: "triceps",
    equipment: "cable",
    level: "intermediate",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Cable_Rope_Overhead_Triceps_Extension/0.jpg`,
    instructions: [
      "Blokka arqon o'rnatib, unga orqa bilan o'girilib, arqonni bosh uzra tuting.",
      "Bir oyoqni oldinga qo'yib, tanani biroz oldinga egib barqaror turing.",
      "Tirsaklarni boshga yaqin tutib, faqat bilaklarni yozib arqonni oldinga cho'zing.",
      "Nazorat ostida arqonni ensa ortiga qaytarib, tricepsda cho'zilishni his qiling.",
    ],
  },
  {
    id: "Seated_Triceps_Press",
    name: "O'tirib Gantel Frantsuz Zhimi",
    englishName: "Seated Triceps Press",
    muscleGroup: "triceps",
    equipment: "dumbbell",
    level: "beginner",
    sets: "3",
    reps: "10-12",
    image: `${IMG_BASE}/Seated_Triceps_Press/0.jpg`,
    instructions: [
      "Skameykaga o'tirib, bitta gantelni ikki kaft bilan bosh uzra ko'tarib tuting.",
      "Tirsaklarni yuqorida, boshga yaqin holatda mahkam tuting.",
      "Faqat bilaklarni bukib, gantelni ensa ortiga sekin tushiring.",
      "Triceps kuchi bilan gantelni yana to'liq yozilguncha ko'taring.",
    ],
  },
  {
    id: "Reverse_Grip_Triceps_Pushdown",
    name: "Teskari Ushlab Pastga Itarish",
    englishName: "Reverse Grip Triceps Pushdown",
    muscleGroup: "triceps",
    equipment: "cable",
    level: "beginner",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Reverse_Grip_Triceps_Pushdown/0.jpg`,
    instructions: [
      "Yuqori blok tutqichini kaftlar yuqoriga qaragan holda ushlang.",
      "Tirsaklarni tanaga yaqin, 90 daraja bukilgan holatda tuting.",
      "Tirsaklarni qimirlatmasdan, tutqichni to'liq pastga itaring.",
      "Pastda tricepsni siqib, nazorat ostida boshlang'ich holatga qaytaring.",
    ],
  },
  {
    id: "Machine_Triceps_Extension",
    name: "Trenajyorda Triceps Yozish",
    englishName: "Machine Triceps Extension",
    muscleGroup: "triceps",
    equipment: "machine",
    level: "beginner",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Machine_Triceps_Extension/0.jpg`,
    instructions: [
      "Trenajyorga o'tirib, tirsaklarni yostiqchaga, bilaklarni tutqichlarga qo'ying.",
      "Orqani tik tutib, ko'krakni tayanchga bosing.",
      "Triceps kuchi bilan tutqichlarni pastga, qo'llar to'liq yozilguncha itaring.",
      "Nazorat ostida qo'llarni boshlang'ich holatga qaytaring.",
    ],
  },

  // Oyoqlar
  {
    id: "Barbell_Squat",
    name: "Shtanga bilan Skvot (O'tirib Turish)",
    englishName: "Barbell Squat",
    muscleGroup: "legs",
    equipment: "barbell",
    level: "beginner",
    sets: "4",
    reps: "6-10",
    image: `${IMG_BASE}/Barbell_Squat/0.jpg`,
    instructions: [
      "Shtangani yelka orqasida, trapetsiya mushaklarida joylashtiring, oyoqlarni yelka kengligida qo'ying.",
      "Ko'krakni tik tutib, dumbani orqaga tortgan holda tizzalarni buka boshlang.",
      "Sonlar yerga parallel bo'lguncha yoki qulaylik chegarasigacha pastga tushing.",
      "Tovon orqali yerni itarib, boshlang'ich tik holatga qayting.",
    ],
  },
  {
    id: "Romanian_Deadlift",
    name: "Rumin Tyagasi (Romanian Deadlift)",
    englishName: "Romanian Deadlift",
    muscleGroup: "legs",
    equipment: "barbell",
    level: "intermediate",
    sets: "4",
    reps: "8-10",
    image: `${IMG_BASE}/Romanian_Deadlift/0.jpg`,
    instructions: [
      "Shtangani sonlar oldida ushlab, tizzalarni yengil bukilgan holatda tik turing.",
      "Belni tekis saqlab, dumbani orqaga chiqargan holda tanani oldinga egib boring.",
      "Shtangani oyoqqa yaqin tutib, orqa son mushaklarida cho'zilishni his qilguncha pastga tushiring.",
      "Orqa son va dumba mushaklari kuchi bilan tik holatga qayting.",
    ],
  },
  {
    id: "Leg_Press",
    name: "Oyoq bilan Itarish (Leg Press)",
    englishName: "Leg Press",
    muscleGroup: "legs",
    equipment: "machine",
    level: "beginner",
    sets: "4",
    reps: "10-12",
    image: `${IMG_BASE}/Leg_Press/0.jpg`,
    instructions: [
      "Trenajyorga o'tirib, oyoqlarni platformada yelka kengligida joylashtiring.",
      "Tizzalarni ko'krak tomon 90 darajagacha bukilguncha platformani sekin pastga tushiring.",
      "Tovon orqali platformani itarib, oyoqlarni to'liq yozmasdan tepaga qaytaring.",
      "Tizzalarni harakat davomida oyoq panjasi yo'nalishida tuting.",
    ],
  },
  {
    id: "Dumbbell_Lunges",
    name: "Gantel bilan Vypad (Lunges)",
    englishName: "Dumbbell Lunges",
    muscleGroup: "legs",
    equipment: "dumbbell",
    level: "beginner",
    sets: "3/oyoq",
    reps: "10-12",
    image: `${IMG_BASE}/Dumbbell_Lunges/0.jpg`,
    instructions: [
      "Gantellarni tana yonida tutib, tik turing.",
      "Bir oyoq bilan oldinga uzun qadam tashlang, orqa tizza yerga yaqinlashguncha pastga tushing.",
      "Old oyoq tovoni bilan itarib, boshlang'ich holatga qayting.",
      "Ikkala oyoqni navbatma-navbat almashtirib takrorlang.",
    ],
  },
  {
    id: "Lying_Leg_Curls",
    name: "Yotib Oyoq Bukish (Leg Curl)",
    englishName: "Lying Leg Curls",
    muscleGroup: "legs",
    equipment: "machine",
    level: "beginner",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Lying_Leg_Curls/0.jpg`,
    instructions: [
      "Trenajyorga yuztuban yoting, to'piqlarni gardishlar ostiga joylashtiring.",
      "Sonlarni trenajyorga bosib, faqat tizzalarni bukib gardishlarni dumbaga tomon torting.",
      "Harakat cho'qqisida orqa son mushaklarini siqing.",
      "Nazorat ostida oyoqlarni to'liq yozilguncha pastga tushiring.",
    ],
  },
  {
    id: "Standing_Calf_Raises",
    name: "Tik Turib Boldir Ko'tarish",
    englishName: "Standing Calf Raises",
    muscleGroup: "legs",
    equipment: "machine",
    level: "beginner",
    sets: "4",
    reps: "15-20",
    image: `${IMG_BASE}/Standing_Calf_Raises/0.jpg`,
    instructions: [
      "Trenajyorda yelkalarni tayanchga qo'yib, oyoq panjalarini platforma chetiga joylashtiring.",
      "Tovonlarni pastga tushirib, boldir mushaklarida to'liq cho'zilishni his qiling.",
      "Oyoq uchlari bilan yuqoriga, imkon qadar baland ko'tariling.",
      "Harakat cho'qqisida bir zum ushlab, nazorat ostida pastga tushiring.",
    ],
  },

  {
    id: "Front_Barbell_Squat",
    name: "Old Skvot (Front Squat)",
    englishName: "Front Barbell Squat",
    muscleGroup: "legs",
    equipment: "barbell",
    level: "expert",
    sets: "4",
    reps: "6-10",
    image: `${IMG_BASE}/Front_Barbell_Squat/0.jpg`,
    instructions: [
      "Shtangani old delta ustida, tirsaklar yuqoriga ko'tarilgan holda yelka oldida tuting.",
      "Oyoqlarni yelka kengligida qo'yib, ko'krakni tik saqlang.",
      "Tirsaklarni baland tutgan holda, sonlar parallelgacha pastga o'tiring.",
      "Tovon orqali itarib, tik holatga qayting — og'irlik old sonlarga tushadi.",
    ],
  },
  {
    id: "Leg_Extensions",
    name: "Trenajyorda Oyoq Yozish",
    englishName: "Leg Extensions",
    muscleGroup: "legs",
    equipment: "machine",
    level: "beginner",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Leg_Extensions/0.jpg`,
    instructions: [
      "Trenajyorga o'tirib, to'piqlarni gardish ostiga joylashtiring, tutqichlarni ushlang.",
      "Old son mushaklari kuchi bilan oyoqlarni to'liq yozilguncha ko'taring.",
      "Cho'qqida old sonni bir zum siqib turing.",
      "Nazorat ostida oyoqlarni boshlang'ich holatga tushiring, og'irlikni tashlamang.",
    ],
  },
  {
    id: "Goblet_Squat",
    name: "Goblet Skvot",
    englishName: "Goblet Squat",
    muscleGroup: "legs",
    equipment: "dumbbell",
    level: "beginner",
    sets: "3",
    reps: "10-12",
    image: `${IMG_BASE}/Goblet_Squat/0.jpg`,
    instructions: [
      "Bitta gantelni ikki kaft bilan vertikal holda ko'krak oldida tuting.",
      "Oyoqlarni yelka kengligidan biroz kengroq qo'yib, oyoq uchlarini biroz tashqariga buring.",
      "Ko'krakni tik tutib, tirsaklar tizzalar orasiga tushguncha chuqur o'tiring.",
      "Tovon orqali itarib, tik holatga qayting.",
    ],
  },
  {
    id: "Barbell_Hip_Thrust",
    name: "Shtanga bilan Hip Thrust",
    englishName: "Barbell Hip Thrust",
    muscleGroup: "legs",
    equipment: "barbell",
    level: "intermediate",
    sets: "4",
    reps: "8-12",
    image: `${IMG_BASE}/Barbell_Hip_Thrust/0.jpg`,
    instructions: [
      "Yelkalarni skameykaga tirab, shtangani son bo'g'imi ustiga joylashtiring.",
      "Oyoq kaftlarini yerga mahkam bosib, tizzalarni 90 daraja bukilgan holatda tuting.",
      "Dumba kuchi bilan sonni yuqoriga, tana tizzadan yelkagacha to'g'ri chiziq bo'lguncha ko'taring.",
      "Cho'qqida dumbani qattiq siqib, nazorat ostida pastga tushiring.",
    ],
  },
  {
    id: "Seated_Calf_Raise",
    name: "O'tirib Boldir Ko'tarish",
    englishName: "Seated Calf Raise",
    muscleGroup: "legs",
    equipment: "machine",
    level: "beginner",
    sets: "4",
    reps: "15-20",
    image: `${IMG_BASE}/Seated_Calf_Raise/0.jpg`,
    instructions: [
      "Trenajyorga o'tirib, tizzalarni yostiqcha ostiga, oyoq panjalarini platforma chetiga qo'ying.",
      "Tovonlarni imkon qadar pastga tushirib, boldirda cho'zilishni his qiling.",
      "Oyoq uchlari bilan yuqoriga, maksimal balandlikka ko'tariling.",
      "Cho'qqida bir zum ushlab turib, sekin pastga tushiring.",
    ],
  },
  {
    id: "Dumbbell_Step_Ups",
    name: "Gantel bilan Kursiga Chiqish",
    englishName: "Dumbbell Step Ups",
    muscleGroup: "legs",
    equipment: "dumbbell",
    level: "beginner",
    sets: "3/oyoq",
    reps: "10-12",
    image: `${IMG_BASE}/Dumbbell_Step_Ups/0.jpg`,
    instructions: [
      "Gantellarni tana yonida tutib, mustahkam skameyka yoki kursi oldida turing.",
      "Bir oyoqni to'liq skameykaga qo'yib, tovon orqali itarib tepaga chiqing.",
      "Tepada bir zum muvozanat saqlab, sekin orqaga tushing.",
      "Bir oyoqda belgilangan takrorni bajarib, keyin oyoqni almashtiring.",
    ],
  },
  {
    id: "Sumo_Deadlift",
    name: "Sumo Stanova Tyaga",
    englishName: "Sumo Deadlift",
    muscleGroup: "legs",
    equipment: "barbell",
    level: "intermediate",
    sets: "4",
    reps: "6-8",
    image: `${IMG_BASE}/Sumo_Deadlift/0.jpg`,
    instructions: [
      "Oyoqlarni yelkadan ancha keng qo'yib, oyoq uchlarini tashqariga buring.",
      "Shtangani oyoqlar orasidan, yelka kengligida ushlang, orqani tekis tuting.",
      "Tovon orqali itarib, shtangani tanaga yaqin tutgan holda tik turguningizcha ko'taring.",
      "Nazorat ostida, orqani egmasdan shtangani pastga qaytaring.",
    ],
  },

  // Qorin
  {
    id: "Plank",
    name: "Plank (Tayanib Turish)",
    englishName: "Plank",
    muscleGroup: "abs",
    equipment: "bodyweight",
    level: "beginner",
    sets: "3",
    reps: "30-45 son.",
    image: `${IMG_BASE}/Plank/0.jpg`,
    instructions: [
      "Tirsaklar va oyoq uchlariga tayanib, tanani boshdan tovongacha bir to'g'ri chiziqqa keltiring.",
      "Qorin va dumba mushaklarini taranglashtirib, belning cho'kib yoki ko'tarilib ketishiga yo'l qo'ymang.",
      "Nafasni erkin, tekis olib turing.",
      "Belgilangan vaqt davomida holatni saqlang.",
    ],
  },
  {
    id: "Crunches",
    name: "Klassik Krunch",
    englishName: "Crunches",
    muscleGroup: "abs",
    equipment: "bodyweight",
    level: "beginner",
    sets: "3",
    reps: "15-20",
    image: `${IMG_BASE}/Crunches/0.jpg`,
    instructions: [
      "Chalqancha yoting, tizzalarni bukib, oyoq kaftlarini yerga tekis qo'ying.",
      "Qo'llarni bosh ortiga yoki ko'krak uzra qo'ying.",
      "Faqat yelka va yuqori tanani qorin kuchi bilan yerdan ko'taring, bel yerdan uzilmasin.",
      "Qorin mushaklarini siqib, sekin boshlang'ich holatga tushing.",
    ],
  },
  {
    id: "Hanging_Leg_Raise",
    name: "Osilib Oyoq Ko'tarish",
    englishName: "Hanging Leg Raise",
    muscleGroup: "abs",
    equipment: "bodyweight",
    level: "expert",
    sets: "3",
    reps: "10-15",
    image: `${IMG_BASE}/Hanging_Leg_Raise/0.jpg`,
    instructions: [
      "Turnikdan osilib, tananing tebranishini to'xtating.",
      "Qorin kuchi bilan to'g'ri oyoqlarni yoki bukilgan tizzalarni yuqoriga ko'taring.",
      "Oyoqlarni imkon qadar yuqoriga, kamida bel sathigacha ko'taring.",
      "Nazorat ostida oyoqlarni sekin pastga tushiring, silkinishga yo'l qo'ymang.",
    ],
  },
  {
    id: "Russian_Twist",
    name: "Rus Burilishi (Russian Twist)",
    englishName: "Russian Twist",
    muscleGroup: "abs",
    equipment: "bodyweight",
    level: "intermediate",
    sets: "3",
    reps: "20 (10/tomon)",
    image: `${IMG_BASE}/Russian_Twist/0.jpg`,
    instructions: [
      "Yerda o'tirib, tizzalarni bukib, tovonlarni yerdan biroz ko'taring yoki yerga tiraying.",
      "Tanani orqaga biroz egib, qorinni taranglashtiring.",
      "Qo'llarni birlashtirib, tanani bir tomondan ikkinchi tomonga buring.",
      "Har ikki tomonga aylanishni tekis va nazorat ostida takrorlang.",
    ],
  },
  {
    id: "Air_Bike",
    name: "Velosiped Krunch (Air Bike)",
    englishName: "Air Bike",
    muscleGroup: "abs",
    equipment: "bodyweight",
    level: "beginner",
    sets: "3",
    reps: "20",
    image: `${IMG_BASE}/Air_Bike/0.jpg`,
    instructions: [
      "Chalqancha yoting, qo'llarni bosh ortiga qo'yib, oyoqlarni yerdan ko'taring.",
      "Bir tizzani ko'krakka tortib, qarama-qarshi tirsakni unga tomon buring.",
      "Oyoqlarni pedal aylantirgandek almashtirib, tananing yon tomonlarini ishga soling.",
      "Harakatni tekis va uzluksiz sur'atda davom ettiring.",
    ],
  },
  {
    id: "Cable_Crunch",
    name: "Blokda Krunch",
    englishName: "Cable Crunch",
    muscleGroup: "abs",
    equipment: "cable",
    level: "beginner",
    sets: "3",
    reps: "15-20",
    image: `${IMG_BASE}/Cable_Crunch/0.jpg`,
    instructions: [
      "Yuqori blok oldida tizza cho'kkalab, arqon tutqichni bosh yoniga ushlang.",
      "Tizzalarni harakatsiz tutib, faqat qorin kuchi bilan tanani pastga buking.",
      "Tirsaklar sonlarga yaqinlashguncha egiling, qorinni siqing.",
      "Nazorat ostida tanani boshlang'ich holatga qaytaring.",
    ],
  },
  {
    id: "Mountain_Climbers",
    name: "Alpinist Mashqi (Mountain Climbers)",
    englishName: "Mountain Climbers",
    muscleGroup: "abs",
    equipment: "bodyweight",
    level: "beginner",
    sets: "3",
    reps: "20 (10/tomon)",
    image: `${IMG_BASE}/Mountain_Climbers/0.jpg`,
    instructions: [
      "Otjimaniye tayanch holatini oling, qo'llar yelka ostida, tana to'g'ri chiziqda.",
      "Bir tizzani ko'krak tomon tez tortib keling.",
      "Sakrab oyoqlarni almashtiring — ikkinchi tizza ko'krakka kelsin.",
      "Dumbani ko'tarmasdan, yugurish sur'atida uzluksiz davom eting.",
    ],
  },
  {
    id: "Ab_Roller",
    name: "G'ildirak bilan Yoyilish (Ab Wheel)",
    englishName: "Ab Roller",
    muscleGroup: "abs",
    equipment: "bodyweight",
    level: "intermediate",
    sets: "3",
    reps: "10-12",
    image: `${IMG_BASE}/Ab_Roller/0.jpg`,
    instructions: [
      "Tizzalab turib, g'ildirak tutqichlarini ikki qo'l bilan ushlang.",
      "Qorinni taranglashtirib, g'ildirakni sekin oldinga yoyib boring.",
      "Belni cho'ktirmasdan, imkon qadar uzoqqa cho'ziling.",
      "Qorin kuchi bilan g'ildirakni orqaga tortib, boshlang'ich holatga qayting.",
    ],
  },
  {
    id: "Reverse_Crunch",
    name: "Teskari Krunch",
    englishName: "Reverse Crunch",
    muscleGroup: "abs",
    equipment: "bodyweight",
    level: "beginner",
    sets: "3",
    reps: "15-20",
    image: `${IMG_BASE}/Reverse_Crunch/0.jpg`,
    instructions: [
      "Chalqancha yotib, qo'llarni tana yonida yerga qo'ying, tizzalarni 90 daraja buking.",
      "Qorinning pastki qismi kuchi bilan tizzalarni ko'krak tomon torting.",
      "Dumbani yerdan biroz ko'tarib, qorinni siqing.",
      "Nazorat ostida oyoqlarni boshlang'ich holatga tushiring, belni yerdan uzmang.",
    ],
  },
  {
    id: "Side_Bridge",
    name: "Yon Plank (Side Plank)",
    englishName: "Side Bridge",
    muscleGroup: "abs",
    equipment: "bodyweight",
    level: "beginner",
    sets: "3",
    reps: "30 son./tomon",
    image: `${IMG_BASE}/Side_Bridge/0.jpg`,
    instructions: [
      "Yonboshlab yotib, tirsakni yelka ostida yerga tiraying.",
      "Sonni yerdan ko'tarib, tanani boshdan tovongacha to'g'ri chiziqqa keltiring.",
      "Qorin yon mushaklarini taranglashtirib, holatni belgilangan vaqt saqlang.",
      "Sekin pastga tushib, ikkinchi tomonga o'girilib takrorlang.",
    ],
  },
  {
    id: "Flat_Bench_Lying_Leg_Raise",
    name: "Yotib Oyoq Ko'tarish",
    englishName: "Flat Bench Lying Leg Raise",
    muscleGroup: "abs",
    equipment: "bodyweight",
    level: "beginner",
    sets: "3",
    reps: "15-20",
    image: `${IMG_BASE}/Flat_Bench_Lying_Leg_Raise/0.jpg`,
    instructions: [
      "Skameyka yoki yerga chalqancha yotib, qo'llar bilan tayanchni ushlang.",
      "Oyoqlarni to'g'ri tutgan holda qorin kuchi bilan tik yuqoriga ko'taring.",
      "Oyoqlar 90 darajaga yetganda qorinni qattiq siqing.",
      "Nazorat ostida oyoqlarni pastga, yerga tegizmasdan tushiring.",
    ],
  },
  {
    id: "Sit-Up",
    name: "Klassik Sit-Up",
    englishName: "Sit-Up",
    muscleGroup: "abs",
    equipment: "bodyweight",
    level: "beginner",
    sets: "3",
    reps: "15-20",
    image: `${IMG_BASE}/Sit-Up/0.jpg`,
    instructions: [
      "Chalqancha yotib, tizzalarni bukib, oyoq kaftlarini yerga qo'ying.",
      "Qo'llarni ko'krakda kesishtiring yoki bosh yoniga qo'ying.",
      "Qorin kuchi bilan butun tanani o'tirgan holatgacha ko'taring.",
      "Sekin, umurtqani birma-bir yerga qo'yib, boshlang'ich holatga qayting.",
    ],
  },
];

// Har bir mashqning manba papkasida boshlang'ich va yakuniy holat suratlari
// (0.jpg / 1.jpg) mavjud — shu ikkisini almashtirib, harakatni "jonlantirish" uchun.
export function getAnimationFrames(exercise: Exercise): [string, string] {
  return [exercise.image, exercise.image.replace("/0.jpg", "/1.jpg")];
}
