export type MuscleGroupId = "chest" | "back" | "shoulders" | "biceps" | "triceps" | "legs" | "abs";

export interface MuscleGroupInfo {
  id: MuscleGroupId;
  label: string;
  icon: string;
}

export const MUSCLE_GROUPS: MuscleGroupInfo[] = [
  { id: "chest", label: "Ko'krak", icon: "fitness_center" },
  { id: "back", label: "Orqa", icon: "rowing" },
  { id: "shoulders", label: "Yelka", icon: "sports_gymnastics" },
  { id: "biceps", label: "Biceps", icon: "sports_martial_arts" },
  { id: "triceps", label: "Triceps", icon: "front_hand" },
  { id: "legs", label: "Oyoqlar", icon: "directions_run" },
  { id: "abs", label: "Qorin", icon: "self_improvement" },
];

export type Equipment = "barbell" | "dumbbell" | "cable" | "machine" | "bodyweight" | "ez-bar";

export const EQUIPMENT_LABELS: Record<Equipment, string> = {
  barbell: "Shtanga",
  dumbbell: "Gantel",
  cable: "Blok Trenajyor",
  machine: "Trenajyor",
  bodyweight: "Tana Og'irligi",
  "ez-bar": "EZ-Shtanga",
};

export type Level = "beginner" | "intermediate" | "expert";

export const LEVEL_LABELS: Record<Level, string> = {
  beginner: "Boshlang'ich",
  intermediate: "O'rta",
  expert: "Yuqori",
};

export interface Exercise {
  id: string;
  name: string;
  englishName: string;
  muscleGroup: MuscleGroupId;
  equipment: Equipment;
  level: Level;
  sets: string;
  reps: string;
  image: string;
  instructions: string[];
}

const IMG_BASE = "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises";

export const EXERCISES: Exercise[] = [
  // Ko'krak
  {
    id: "Barbell_Bench_Press_-_Medium_Grip",
    name: "Shtanga Yotib Zhim (O'rta Ushlab)",
    englishName: "Barbell Bench Press - Medium Grip",
    muscleGroup: "chest",
    equipment: "barbell",
    level: "beginner",
    sets: "4",
    reps: "6-10",
    image: `${IMG_BASE}/Barbell_Bench_Press_-_Medium_Grip/0.jpg`,
    instructions: [
      "Skameykaga yoting, oyoqlaringizni yerga mahkam tiraying, kurak suyaklaringizni orqaga siqing.",
      "Shtangani yelkadan biroz kengroq ushlab, ko'krak markazidan olib chiqing.",
      "Sekin nafas olib, shtangani ko'krakning pastki qismiga qadar tushiring.",
      "Nafasni chiqarib, tirsaklarni tanaga yaqin tutgan holda tepaga itaring.",
    ],
  },
  {
    id: "Incline_Dumbbell_Press",
    name: "Qiya Skameykada Gantel Zhim",
    englishName: "Incline Dumbbell Press",
    muscleGroup: "chest",
    equipment: "dumbbell",
    level: "beginner",
    sets: "4",
    reps: "8-12",
    image: `${IMG_BASE}/Incline_Dumbbell_Press/0.jpg`,
    instructions: [
      "Skameykani 30-45 daraja qiyalikka o'rnating va gantellarni tizzalarga qo'yib o'tiring.",
      "Har ikki oyoq bilan itarib, gantellarni ko'krak sathigacha ko'taring.",
      "Gantellarni yelka chizig'ida ushlab, sekin ko'krakning yuqori qismigacha tushiring.",
      "To'liq nazorat bilan yuqoriga itarib, tepada gantellarni bir-biriga yaqinlashtiring.",
    ],
  },
  {
    id: "Dumbbell_Flyes",
    name: "Gantel Razvedeniya",
    englishName: "Dumbbell Flyes",
    muscleGroup: "chest",
    equipment: "dumbbell",
    level: "beginner",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Dumbbell_Flyes/0.jpg`,
    instructions: [
      "Skameykada yoting, gantellarni ko'krak uzra tutib, tirsaklarni biroz bukilgan holda saqlang.",
      "Tirsak burchagini o'zgartirmasdan, qo'llarni yon tomonlarga yoyib tushiring.",
      "Ko'krak mushaklarida cho'zilishni his qilguningizcha pastga tushiring.",
      "Ko'krak mushaklarini siqib, gantellarni boshlang'ich holatga qaytaring.",
    ],
  },
  {
    id: "Pushups",
    name: "Klassik Otjimaniye (Push-Up)",
    englishName: "Pushups",
    muscleGroup: "chest",
    equipment: "bodyweight",
    level: "beginner",
    sets: "3",
    reps: "12-20",
    image: `${IMG_BASE}/Pushups/0.jpg`,
    instructions: [
      "Qo'llarni yelkadan biroz kengroq qo'yib tayanch holatini oling, tana bir chiziqda bo'lsin.",
      "Qorin va dumba mushaklarini taranglashtirib, tananing egilib ketishiga yo'l qo'ymang.",
      "Tirsaklarni yon tomonga qarab bukib, ko'krak yerga yaqinlashguncha tushing.",
      "Kaftlarni yerga bosib, boshlang'ich holatga qayting.",
    ],
  },
  {
    id: "Dips_-_Chest_Version",
    name: "Bruslarda Tushish (Ko'krakka)",
    englishName: "Dips - Chest Version",
    muscleGroup: "chest",
    equipment: "bodyweight",
    level: "intermediate",
    sets: "3",
    reps: "8-12",
    image: `${IMG_BASE}/Dips_-_Chest_Version/0.jpg`,
    instructions: [
      "Bruslarni ushlab tananing tepasiga chiqing, tanani biroz oldinga egib turing.",
      "Tirsaklarni yon tomonga yoyib, sekin pastga tushing.",
      "Ko'krakda cho'zilish sezilguncha yoki yelka 90 darajaga yetguncha tushing.",
      "Ko'krak mushaklarini ishga solib, boshlang'ich holatga ko'tariling.",
    ],
  },
  {
    id: "Cable_Crossover",
    name: "Blokli Trenajyorda Krossover",
    englishName: "Cable Crossover",
    muscleGroup: "chest",
    equipment: "cable",
    level: "beginner",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Cable_Crossover/0.jpg`,
    instructions: [
      "Ikkala blok tutqichini yuqoriga o'rnatib, tanani biroz oldinga egib, markazda turing.",
      "Tirsaklarni yengil bukilgan holatda tutib, qo'llarni pastga va oldinga tortib olib keling.",
      "Qo'llarni qorin oldida kesishtirib, ko'krakni maksimal siqing.",
      "Nazorat ostida qo'llarni boshlang'ich holatga qaytaring.",
    ],
  },

  // Orqa
  {
    id: "Pullups",
    name: "Turnikda Tortilish",
    englishName: "Pullups",
    muscleGroup: "back",
    equipment: "bodyweight",
    level: "intermediate",
    sets: "4",
    reps: "6-10",
    image: `${IMG_BASE}/Pullups/0.jpg`,
    instructions: [
      "Turnikni yelkadan kengroq ushlab, tananing to'liq osilishiga yo'l qo'ying.",
      "Kurak suyaklarini pastga va orqaga tortib harakatni boshlang.",
      "Iyagingiz turnikdan oshguncha tanani yuqoriga tortib chiqing.",
      "Sekin va nazorat ostida boshlang'ich holatga tushing.",
    ],
  },
  {
    id: "Bent_Over_Barbell_Row",
    name: "Egilgan Holda Shtanga Tortish",
    englishName: "Bent Over Barbell Row",
    muscleGroup: "back",
    equipment: "barbell",
    level: "beginner",
    sets: "4",
    reps: "8-10",
    image: `${IMG_BASE}/Bent_Over_Barbell_Row/0.jpg`,
    instructions: [
      "Oyoqlarni yelka kengligida qo'yib, tizzalarni biroz bukib, tanani 45 daraja egib turing.",
      "Orqa tekis holatda, shtangani yelkadan biroz kengroq ushlang.",
      "Tirsaklarni orqaga tortib, shtangani qorin pastki qismiga qadar ko'taring.",
      "Kuraklarni siqib, sekin boshlang'ich holatga tushiring.",
    ],
  },
  {
    id: "Wide-Grip_Lat_Pulldown",
    name: "Keng Ushlab Yuqori Blok Tortish",
    englishName: "Wide-Grip Lat Pulldown",
    muscleGroup: "back",
    equipment: "cable",
    level: "beginner",
    sets: "4",
    reps: "10-12",
    image: `${IMG_BASE}/Wide-Grip_Lat_Pulldown/0.jpg`,
    instructions: [
      "Trenajyorda o'tirib, tayanchni tizzalar ustiga mahkamlang, tutqichni yelkadan kengroq ushlang.",
      "Ko'krakni biroz ko'tarib, tortish paytida orqaga yaslanmang.",
      "Tutqichni ko'krakning yuqori qismiga qadar tortib tushiring, kuraklarni siqing.",
      "Nazorat ostida tutqichni yuqoriga, boshlang'ich holatga qaytaring.",
    ],
  },
  {
    id: "Seated_Cable_Rows",
    name: "O'tirib Blokda Tortish",
    englishName: "Seated Cable Rows",
    muscleGroup: "back",
    equipment: "cable",
    level: "beginner",
    sets: "3",
    reps: "10-12",
    image: `${IMG_BASE}/Seated_Cable_Rows/0.jpg`,
    instructions: [
      "Trenajyorda o'tirib, tizzalarni yengil bukib, oyoqlarni tayanchga tiraying.",
      "Orqani tik tutgan holda tutqichni ikki qo'l bilan ushlang.",
      "Tirsaklarni tanaga yaqin tutib, tutqichni qorin tomon tortib keling, kuraklarni siqing.",
      "Sekin nazorat bilan qo'llarni oldinga, boshlang'ich holatga qaytaring.",
    ],
  },
  {
    id: "One-Arm_Dumbbell_Row",
    name: "Bir Qo'lda Gantel Tortish",
    englishName: "One-Arm Dumbbell Row",
    muscleGroup: "back",
    equipment: "dumbbell",
    level: "beginner",
    sets: "3/qo'l",
    reps: "10-12",
    image: `${IMG_BASE}/One-Arm_Dumbbell_Row/0.jpg`,
    instructions: [
      "Bir tizza va qo'lni skameykaga tirab, orqani tekis tuting.",
      "Ikkinchi qo'lda gantelni tutib, qo'lni to'liq osiltiring.",
      "Tirsakni orqaga tortib, gantelni bel yoniga qadar ko'taring, kurakni siqing.",
      "Nazorat ostida gantelni pastga, boshlang'ich holatga tushiring.",
    ],
  },
  {
    id: "Barbell_Deadlift",
    name: "Stanova Tyaga (Ko'tarish)",
    englishName: "Barbell Deadlift",
    muscleGroup: "back",
    equipment: "barbell",
    level: "intermediate",
    sets: "4",
    reps: "5-8",
    image: `${IMG_BASE}/Barbell_Deadlift/0.jpg`,
    instructions: [
      "Shtangaga oyoq yelka kengligida yaqin turing, orqani tekis tutib pastga egiling.",
      "Shtangani yelkadan biroz kengroq ushlab, ko'krakni ko'tarib, belni tekis saqlang.",
      "Oyoq va son mushaklari kuchi bilan shtangani tanaga yaqin tutib tik turguningizcha ko'taring.",
      "Bel va orqani egmasdan, harakatni teskari tartibda pastga tushirib boshlang'ich holatga qayting.",
    ],
  },

  // Yelka
  {
    id: "Standing_Military_Press",
    name: "Tik Turib Shtanga Bosh Uzra Zhim",
    englishName: "Standing Military Press",
    muscleGroup: "shoulders",
    equipment: "barbell",
    level: "beginner",
    sets: "4",
    reps: "6-10",
    image: `${IMG_BASE}/Standing_Military_Press/0.jpg`,
    instructions: [
      "Oyoqlarni yelka kengligida qo'yib, shtangani yelka sathida, kaftlar oldinga qaragan holda ushlang.",
      "Qorin va dumba mushaklarini taranglashtirib, tanani barqaror tuting.",
      "Shtangani boshdan bir oz nari o'tkazib, tik yuqoriga qo'llar to'liq yozilguncha itaring.",
      "Nazorat ostida shtangani yelka sathiga qaytaring.",
    ],
  },
  {
    id: "Arnold_Dumbbell_Press",
    name: "Arnold Zhimi",
    englishName: "Arnold Dumbbell Press",
    muscleGroup: "shoulders",
    equipment: "dumbbell",
    level: "intermediate",
    sets: "3",
    reps: "8-12",
    image: `${IMG_BASE}/Arnold_Dumbbell_Press/0.jpg`,
    instructions: [
      "O'tirib yoki tik turib, gantellarni kaftlar tanaga qaragan holda ko'krak oldida tuting.",
      "Gantellarni yuqoriga ko'tarayotganda bilaklarni asta tashqariga aylantiring.",
      "Harakat oxirida kaftlar oldinga qaragan holda qo'llarni to'liq yozing.",
      "Xuddi shu aylanma yo'l bilan gantellarni boshlang'ich holatga qaytaring.",
    ],
  },
  {
    id: "Side_Lateral_Raise",
    name: "Gantelni Yon Tomonga Ko'tarish",
    englishName: "Side Lateral Raise",
    muscleGroup: "shoulders",
    equipment: "dumbbell",
    level: "beginner",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Side_Lateral_Raise/0.jpg`,
    instructions: [
      "Tik turib, gantellarni tana yoniga tutib, tirsaklarni yengil bukilgan holatda saqlang.",
      "Qo'llarni yon tomonga, yelka sathigacha ko'taring, kaftlar yerga qaragan bo'lsin.",
      "Harakatni tanani tebratmasdan, faqat yelka kuchi bilan bajaring.",
      "Nazorat ostida gantellarni sekin pastga tushiring.",
    ],
  },
  {
    id: "Front_Dumbbell_Raise",
    name: "Gantelni Oldinga Ko'tarish",
    englishName: "Front Dumbbell Raise",
    muscleGroup: "shoulders",
    equipment: "dumbbell",
    level: "beginner",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Front_Dumbbell_Raise/0.jpg`,
    instructions: [
      "Tik turib, gantellarni tana oldida, kaftlar sonlarga qaragan holda ushlang.",
      "Bir yoki ikkala qo'lni tirsak biroz bukilgan holda oldinga, yelka sathigacha ko'taring.",
      "Harakat cho'qqisida bir zum ushlab turing, tananing ortga egilishiga yo'l qo'ymang.",
      "Sekin nazorat bilan gantellarni boshlang'ich holatga tushiring.",
    ],
  },
  {
    id: "Face_Pull",
    name: "Yuzga Tortish (Face Pull)",
    englishName: "Face Pull",
    muscleGroup: "shoulders",
    equipment: "cable",
    level: "intermediate",
    sets: "3",
    reps: "15-20",
    image: `${IMG_BASE}/Face_Pull/0.jpg`,
    instructions: [
      "Blokni yuz sathida o'rnatib, arqon tutqichni ikki uchidan ushlang.",
      "Tirsaklarni yuqori va yon tomonga ko'tarib, arqonni yuzga tomon tortib keling.",
      "Tortish paytida bilaklarni tashqariga aylantirib, orqa yelka mushaklarini siqing.",
      "Nazorat ostida qo'llarni oldinga, boshlang'ich holatga qaytaring.",
    ],
  },
  {
    id: "Upright_Barbell_Row",
    name: "Shtangani Tik Tortish",
    englishName: "Upright Barbell Row",
    muscleGroup: "shoulders",
    equipment: "barbell",
    level: "beginner",
    sets: "3",
    reps: "10-12",
    image: `${IMG_BASE}/Upright_Barbell_Row/0.jpg`,
    instructions: [
      "Shtangani yelka kengligida ushlab, tana oldida osiltirib tik turing.",
      "Tirsaklarni yuqoriga yo'naltirib, shtangani iyak sathigacha ko'taring.",
      "Shtangani tanaga yaqin tutib, yelka va trapetsiya mushaklarini ishga soling.",
      "Nazorat ostida shtangani boshlang'ich holatga tushiring.",
    ],
  },

  // Biceps
  {
    id: "Barbell_Curl",
    name: "Shtanga bilan Bilak Bukish",
    englishName: "Barbell Curl",
    muscleGroup: "biceps",
    equipment: "barbell",
    level: "beginner",
    sets: "3",
    reps: "8-12",
    image: `${IMG_BASE}/Barbell_Curl/0.jpg`,
    instructions: [
      "Oyoqlarni yelka kengligida qo'yib, shtangani kaftlar oldinga qaragan holda ushlang.",
      "Tirsaklarni tanaga yaqin tutib, faqat bilaklarni bukib shtangani ko'taring.",
      "Harakat cho'qqisida bitseps mushaklarini siqing, tananing tebranishiga yo'l qo'ymang.",
      "Sekin nazorat bilan shtangani boshlang'ich holatga tushiring.",
    ],
  },
  {
    id: "Seated_Dumbbell_Curl",
    name: "O'tirib Gantel bilan Bilak Bukish",
    englishName: "Seated Dumbbell Curl",
    muscleGroup: "biceps",
    equipment: "dumbbell",
    level: "beginner",
    sets: "3",
    reps: "10-12",
    image: `${IMG_BASE}/Seated_Dumbbell_Curl/0.jpg`,
    instructions: [
      "Skameykada o'tirib, gantellarni yon tomonda, kaftlar tanaga qaragan holda tuting.",
      "Bilaklarni bukayotganda kaftni tashqariga aylantirib, ko'targan qo'lni yelkaga yaqinlashtiring.",
      "Tirsakni harakat davomida qimirlatmang, faqat bilak ishlasin.",
      "Nazorat ostida gantelni boshlang'ich holatga tushiring va navbatma-navbat bajaring.",
    ],
  },
  {
    id: "Hammer_Curls",
    name: "Bolg'a Uslubida Bukish (Hammer Curl)",
    englishName: "Hammer Curls",
    muscleGroup: "biceps",
    equipment: "dumbbell",
    level: "beginner",
    sets: "3",
    reps: "10-12",
    image: `${IMG_BASE}/Hammer_Curls/0.jpg`,
    instructions: [
      "Tik turib, gantellarni kaftlar bir-biriga qaragan holda tana yonida tuting.",
      "Kaft holatini o'zgartirmasdan, gantellarni yelkaga tomon bukib ko'taring.",
      "Tirsaklarni tanaga yaqin tutib, harakatni faqat bilak kuchi bilan bajaring.",
      "Sekin nazorat bilan gantellarni boshlang'ich holatga tushiring.",
    ],
  },
  {
    id: "Preacher_Curl",
    name: "Skameykada Bilak Bukish (Preacher Curl)",
    englishName: "Preacher Curl",
    muscleGroup: "biceps",
    equipment: "barbell",
    level: "beginner",
    sets: "3",
    reps: "10-12",
    image: `${IMG_BASE}/Preacher_Curl/0.jpg`,
    instructions: [
      "Preacher skameykasiga o'tirib, qo'llaringizni qo'ltiq ostigacha tayanchga qo'ying.",
      "Shtanga yoki EZ-shtangani kaftlar yuqoriga qaragan holda ushlang.",
      "Faqat bilaklarni bukib, shtangani yelka tomon ko'taring, tirsaklarni tayanchdan uzmang.",
      "Nazorat ostida shtangani to'liq yozilguncha pastga tushiring.",
    ],
  },
  {
    id: "Concentration_Curls",
    name: "Konsentratsiyali Bukish",
    englishName: "Concentration Curls",
    muscleGroup: "biceps",
    equipment: "dumbbell",
    level: "beginner",
    sets: "3/qo'l",
    reps: "12-15",
    image: `${IMG_BASE}/Concentration_Curls/0.jpg`,
    instructions: [
      "Skameykaga o'tirib, tirsakni son ichki qismiga tirab gantelni ushlang.",
      "Tanani biroz oldinga egib, qo'lni to'liq osiltiring.",
      "Faqat bilak kuchi bilan gantelni yelka tomon bukib ko'taring va bitsepsni siqing.",
      "Sekin nazorat bilan gantelni boshlang'ich holatga tushiring.",
    ],
  },
  {
    id: "Standing_Biceps_Cable_Curl",
    name: "Blokda Tik Turib Bilak Bukish",
    englishName: "Standing Biceps Cable Curl",
    muscleGroup: "biceps",
    equipment: "cable",
    level: "beginner",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Standing_Biceps_Cable_Curl/0.jpg`,
    instructions: [
      "Pastki blokka tutqich o'rnatib, undan bir necha qadam nariga turing.",
      "Tirsaklarni tanaga yaqin tutib, tutqichni yelka tomon bukib tortib keling.",
      "Harakat cho'qqisida bitseps mushaklarini siqing.",
      "Nazorat ostida tutqichni boshlang'ich holatga qaytaring.",
    ],
  },

  // Triceps
  {
    id: "Close-Grip_Barbell_Bench_Press",
    name: "Tor Ushlab Shtanga Yotib Zhim",
    englishName: "Close-Grip Barbell Bench Press",
    muscleGroup: "triceps",
    equipment: "barbell",
    level: "beginner",
    sets: "4",
    reps: "8-10",
    image: `${IMG_BASE}/Close-Grip_Barbell_Bench_Press/0.jpg`,
    instructions: [
      "Skameykaga yoting, shtangani yelka kengligidan torroq ushlang.",
      "Tirsaklarni tanaga yaqin tutib, shtangani ko'krakning pastki qismiga tushiring.",
      "Tirsaklar tashqariga yoyilmasin, faqat triceps kuchi bilan yuqoriga iting.",
      "Qo'llar to'liq yozilguncha shtangani ko'tarib, boshlang'ich holatni tiklang.",
    ],
  },
  {
    id: "Triceps_Pushdown",
    name: "Blokda Tricepsni Pastga Itarish",
    englishName: "Triceps Pushdown",
    muscleGroup: "triceps",
    equipment: "cable",
    level: "beginner",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Triceps_Pushdown/0.jpg`,
    instructions: [
      "Yuqori blokka tutqich o'rnatib, tirsaklarni tanaga yaqin, 90 daraja bukilgan holda tuting.",
      "Tirsaklarni qimirlatmasdan, tutqichni to'liq pastga, qo'llar yozilguncha itaring.",
      "Harakat pastida triceps mushaklarini bir zum siqing.",
      "Nazorat ostida tutqichni yuqoriga, boshlang'ich holatga qaytaring.",
    ],
  },
  {
    id: "Lying_Triceps_Press",
    name: "Yotib Peshonaga Tushirish (Skull Crusher)",
    englishName: "Lying Triceps Press",
    muscleGroup: "triceps",
    equipment: "ez-bar",
    level: "intermediate",
    sets: "3",
    reps: "10-12",
    image: `${IMG_BASE}/Lying_Triceps_Press/0.jpg`,
    instructions: [
      "Skameykaga yoting, EZ-shtangani qo'llar tepada, ko'krak uzra tik tutib ushlang.",
      "Faqat tirsaklarni bukib, shtangani peshona yoki bosh ortiga sekin tushiring.",
      "Tirsaklarni harakat davomida bir joyda, tanaga perpendikulyar tuting.",
      "Triceps kuchi bilan shtangani boshlang'ich holatga qaytaring.",
    ],
  },
  {
    id: "Standing_Dumbbell_Triceps_Extension",
    name: "Tik Turib Gantelni Bosh Uzra Cho'zish",
    englishName: "Standing Dumbbell Triceps Extension",
    muscleGroup: "triceps",
    equipment: "dumbbell",
    level: "beginner",
    sets: "3",
    reps: "10-12",
    image: `${IMG_BASE}/Standing_Dumbbell_Triceps_Extension/0.jpg`,
    instructions: [
      "Tik turib, bitta gantelni ikki qo'l bilan bosh uzra ko'tarib ushlang.",
      "Tirsaklarni yuqorida, boshga yaqin tutib, faqat bilaklarni bukib gantelni ensa ortiga tushiring.",
      "Tirsaklarni tashqariga yoyilishiga yo'l qo'ymang.",
      "Triceps kuchi bilan gantelni yana bosh uzra to'liq yozilguncha ko'taring.",
    ],
  },
  {
    id: "Dips_-_Triceps_Version",
    name: "Bruslarda Tushish (Tricepsga)",
    englishName: "Dips - Triceps Version",
    muscleGroup: "triceps",
    equipment: "bodyweight",
    level: "beginner",
    sets: "3",
    reps: "8-12",
    image: `${IMG_BASE}/Dips_-_Triceps_Version/0.jpg`,
    instructions: [
      "Bruslarni ushlab, tanani tik holatda tutib tepaga chiqing.",
      "Tirsaklarni tanaga yaqin, orqaga qarab bukib, sekin pastga tushing.",
      "Yelka bilan tirsak bir chiziqqa yetguncha yoki qulaylik chegarasigacha tushing.",
      "Triceps kuchi bilan tananing tepasiga qaytaring, tirsaklarni yon tomonga yoymang.",
    ],
  },
  {
    id: "Tricep_Dumbbell_Kickback",
    name: "Egilgan Holda Gantel Kikbek",
    englishName: "Tricep Dumbbell Kickback",
    muscleGroup: "triceps",
    equipment: "dumbbell",
    level: "beginner",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Tricep_Dumbbell_Kickback/0.jpg`,
    instructions: [
      "Bir tizza va qo'lni skameykaga tirab, tanani yerga parallel tuting.",
      "Gantelli qo'lning tirsagini tanaga yaqin, 90 daraja bukilgan holda ushlang.",
      "Faqat bilakni yozib, gantelni orqaga, qo'l to'liq tekis bo'lguncha iting.",
      "Harakat oxirida triceps mushagini siqib, nazorat ostida boshlang'ich holatga qayting.",
    ],
  },

  // Oyoqlar
  {
    id: "Barbell_Squat",
    name: "Shtanga bilan Skvot (O'tirib Turish)",
    englishName: "Barbell Squat",
    muscleGroup: "legs",
    equipment: "barbell",
    level: "beginner",
    sets: "4",
    reps: "6-10",
    image: `${IMG_BASE}/Barbell_Squat/0.jpg`,
    instructions: [
      "Shtangani yelka orqasida, trapetsiya mushaklarida joylashtiring, oyoqlarni yelka kengligida qo'ying.",
      "Ko'krakni tik tutib, dumbani orqaga tortgan holda tizzalarni buka boshlang.",
      "Sonlar yerga parallel bo'lguncha yoki qulaylik chegarasigacha pastga tushing.",
      "Tovon orqali yerni itarib, boshlang'ich tik holatga qayting.",
    ],
  },
  {
    id: "Romanian_Deadlift",
    name: "Rumin Tyagasi (Romanian Deadlift)",
    englishName: "Romanian Deadlift",
    muscleGroup: "legs",
    equipment: "barbell",
    level: "intermediate",
    sets: "4",
    reps: "8-10",
    image: `${IMG_BASE}/Romanian_Deadlift/0.jpg`,
    instructions: [
      "Shtangani sonlar oldida ushlab, tizzalarni yengil bukilgan holatda tik turing.",
      "Belni tekis saqlab, dumbani orqaga chiqargan holda tanani oldinga egib boring.",
      "Shtangani oyoqqa yaqin tutib, orqa son mushaklarida cho'zilishni his qilguncha pastga tushiring.",
      "Orqa son va dumba mushaklari kuchi bilan tik holatga qayting.",
    ],
  },
  {
    id: "Leg_Press",
    name: "Oyoq bilan Itarish (Leg Press)",
    englishName: "Leg Press",
    muscleGroup: "legs",
    equipment: "machine",
    level: "beginner",
    sets: "4",
    reps: "10-12",
    image: `${IMG_BASE}/Leg_Press/0.jpg`,
    instructions: [
      "Trenajyorga o'tirib, oyoqlarni platformada yelka kengligida joylashtiring.",
      "Tizzalarni ko'krak tomon 90 darajagacha bukilguncha platformani sekin pastga tushiring.",
      "Tovon orqali platformani itarib, oyoqlarni to'liq yozmasdan tepaga qaytaring.",
      "Tizzalarni harakat davomida oyoq panjasi yo'nalishida tuting.",
    ],
  },
  {
    id: "Dumbbell_Lunges",
    name: "Gantel bilan Vypad (Lunges)",
    englishName: "Dumbbell Lunges",
    muscleGroup: "legs",
    equipment: "dumbbell",
    level: "beginner",
    sets: "3/oyoq",
    reps: "10-12",
    image: `${IMG_BASE}/Dumbbell_Lunges/0.jpg`,
    instructions: [
      "Gantellarni tana yonida tutib, tik turing.",
      "Bir oyoq bilan oldinga uzun qadam tashlang, orqa tizza yerga yaqinlashguncha pastga tushing.",
      "Old oyoq tovoni bilan itarib, boshlang'ich holatga qayting.",
      "Ikkala oyoqni navbatma-navbat almashtirib takrorlang.",
    ],
  },
  {
    id: "Lying_Leg_Curls",
    name: "Yotib Oyoq Bukish (Leg Curl)",
    englishName: "Lying Leg Curls",
    muscleGroup: "legs",
    equipment: "machine",
    level: "beginner",
    sets: "3",
    reps: "12-15",
    image: `${IMG_BASE}/Lying_Leg_Curls/0.jpg`,
    instructions: [
      "Trenajyorga yuztuban yoting, to'piqlarni gardishlar ostiga joylashtiring.",
      "Sonlarni trenajyorga bosib, faqat tizzalarni bukib gardishlarni dumbaga tomon torting.",
      "Harakat cho'qqisida orqa son mushaklarini siqing.",
      "Nazorat ostida oyoqlarni to'liq yozilguncha pastga tushiring.",
    ],
  },
  {
    id: "Standing_Calf_Raises",
    name: "Tik Turib Boldir Ko'tarish",
    englishName: "Standing Calf Raises",
    muscleGroup: "legs",
    equipment: "machine",
    level: "beginner",
    sets: "4",
    reps: "15-20",
    image: `${IMG_BASE}/Standing_Calf_Raises/0.jpg`,
    instructions: [
      "Trenajyorda yelkalarni tayanchga qo'yib, oyoq panjalarini platforma chetiga joylashtiring.",
      "Tovonlarni pastga tushirib, boldir mushaklarida to'liq cho'zilishni his qiling.",
      "Oyoq uchlari bilan yuqoriga, imkon qadar baland ko'tariling.",
      "Harakat cho'qqisida bir zum ushlab, nazorat ostida pastga tushiring.",
    ],
  },

  // Qorin
  {
    id: "Plank",
    name: "Plank (Tayanib Turish)",
    englishName: "Plank",
    muscleGroup: "abs",
    equipment: "bodyweight",
    level: "beginner",
    sets: "3",
    reps: "30-45 son.",
    image: `${IMG_BASE}/Plank/0.jpg`,
    instructions: [
      "Tirsaklar va oyoq uchlariga tayanib, tanani boshdan tovongacha bir to'g'ri chiziqqa keltiring.",
      "Qorin va dumba mushaklarini taranglashtirib, belning cho'kib yoki ko'tarilib ketishiga yo'l qo'ymang.",
      "Nafasni erkin, tekis olib turing.",
      "Belgilangan vaqt davomida holatni saqlang.",
    ],
  },
  {
    id: "Crunches",
    name: "Klassik Krunch",
    englishName: "Crunches",
    muscleGroup: "abs",
    equipment: "bodyweight",
    level: "beginner",
    sets: "3",
    reps: "15-20",
    image: `${IMG_BASE}/Crunches/0.jpg`,
    instructions: [
      "Chalqancha yoting, tizzalarni bukib, oyoq kaftlarini yerga tekis qo'ying.",
      "Qo'llarni bosh ortiga yoki ko'krak uzra qo'ying.",
      "Faqat yelka va yuqori tanani qorin kuchi bilan yerdan ko'taring, bel yerdan uzilmasin.",
      "Qorin mushaklarini siqib, sekin boshlang'ich holatga tushing.",
    ],
  },
  {
    id: "Hanging_Leg_Raise",
    name: "Osilib Oyoq Ko'tarish",
    englishName: "Hanging Leg Raise",
    muscleGroup: "abs",
    equipment: "bodyweight",
    level: "expert",
    sets: "3",
    reps: "10-15",
    image: `${IMG_BASE}/Hanging_Leg_Raise/0.jpg`,
    instructions: [
      "Turnikdan osilib, tananing tebranishini to'xtating.",
      "Qorin kuchi bilan to'g'ri oyoqlarni yoki bukilgan tizzalarni yuqoriga ko'taring.",
      "Oyoqlarni imkon qadar yuqoriga, kamida bel sathigacha ko'taring.",
      "Nazorat ostida oyoqlarni sekin pastga tushiring, silkinishga yo'l qo'ymang.",
    ],
  },
  {
    id: "Russian_Twist",
    name: "Rus Burilishi (Russian Twist)",
    englishName: "Russian Twist",
    muscleGroup: "abs",
    equipment: "bodyweight",
    level: "intermediate",
    sets: "3",
    reps: "20 (10/tomon)",
    image: `${IMG_BASE}/Russian_Twist/0.jpg`,
    instructions: [
      "Yerda o'tirib, tizzalarni bukib, tovonlarni yerdan biroz ko'taring yoki yerga tiraying.",
      "Tanani orqaga biroz egib, qorinni taranglashtiring.",
      "Qo'llarni birlashtirib, tanani bir tomondan ikkinchi tomonga buring.",
      "Har ikki tomonga aylanishni tekis va nazorat ostida takrorlang.",
    ],
  },
  {
    id: "Air_Bike",
    name: "Velosiped Krunch (Air Bike)",
    englishName: "Air Bike",
    muscleGroup: "abs",
    equipment: "bodyweight",
    level: "beginner",
    sets: "3",
    reps: "20",
    image: `${IMG_BASE}/Air_Bike/0.jpg`,
    instructions: [
      "Chalqancha yoting, qo'llarni bosh ortiga qo'yib, oyoqlarni yerdan ko'taring.",
      "Bir tizzani ko'krakka tortib, qarama-qarshi tirsakni unga tomon buring.",
      "Oyoqlarni pedal aylantirgandek almashtirib, tananing yon tomonlarini ishga soling.",
      "Harakatni tekis va uzluksiz sur'atda davom ettiring.",
    ],
  },
  {
    id: "Cable_Crunch",
    name: "Blokda Krunch",
    englishName: "Cable Crunch",
    muscleGroup: "abs",
    equipment: "cable",
    level: "beginner",
    sets: "3",
    reps: "15-20",
    image: `${IMG_BASE}/Cable_Crunch/0.jpg`,
    instructions: [
      "Yuqori blok oldida tizza cho'kkalab, arqon tutqichni bosh yoniga ushlang.",
      "Tizzalarni harakatsiz tutib, faqat qorin kuchi bilan tanani pastga buking.",
      "Tirsaklar sonlarga yaqinlashguncha egiling, qorinni siqing.",
      "Nazorat ostida tanani boshlang'ich holatga qaytaring.",
    ],
  },
];

// Har bir mashqning manba papkasida boshlang'ich va yakuniy holat suratlari
// (0.jpg / 1.jpg) mavjud — shu ikkisini almashtirib, harakatni "jonlantirish" uchun.
export function getAnimationFrames(exercise: Exercise): [string, string] {
  return [exercise.image, exercise.image.replace("/0.jpg", "/1.jpg")];
}
